### ISSUE TITLE
realTextureFileName in plist for cocos2d is empty

### ISSUE THREAD

**Issue by ilkarataev** [odrick/gulp-free-tex-packer#2]
Hi i am sorry maybe qestion is stupid but when i build textures from gulp    <key>realTextureFileName</key> had epmty string            <string></string>.
When i built it on desktop app version 0.6.6. that key had textures name.
I think you fix it bug but not release in gulp.
best Regads
and thank you for you work.

**Comment by ilkarataev** [comment]
find the error in node_modules/free-tex-packer-core/exporters/Cocos2d.mst name imageFile change to imageName. Maybe it's only temporary solution.
```
      <key>realTextureFileName</key>
      <string><%config.imageFile%></string>
      <key>size</key>
      <string>{<%config.imageWidth%>,<%config.imageHeight%>}</string>
      <key>textureFileName</key>
      <string><%config.imageName%></string>
    </dict>
```

**Comment by odrick** [comment]
Fixed
